### ISSUE TITLE
readlink: illegal option -- f on macOS

### ISSUE THREAD

**Issue by ChristopherDosin** [shopware/production#3]
While executing `bin/build-js.sh` i got the error `readlink: illegal option -- f` on macOS 10.14. 
That resulted in an npm error because the project root path was wrong. 

**Error Log**
[The full error log](https://gist.github.com/ChristopherDosin/062dccf596eb4396d8b9d39ec1801e41)

This error was related to readlink on macOS: 
https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

I solved the problem with `brew install coreutils` and then changed the [following line](https://github.com/shopware/production/blob/6.1/bin/build-js.sh#L3) to 

`export PROJECT_ROOT="${PROJECT_ROOT:-"$(dirname $(dirname $(greadlink -f "$0")))"}"`

e.g changed `readlink` to `greadlink`.

Now the npm installation runs without problems.

**Comment by pweyck** [comment]
Hello @ChristopherDosin ,

Thanks for reporting this issue. It should be fixed with the https://github.com/shopware/production/releases/tag/v6.1.0-rc4 release. 

But it should not be necessary anymore to build the javascript, because they are now prebuild into https://github.com/shopware/storefront/releases/tag/v6.1.0-rc4 and https://github.com/shopware/administration/releases/tag/v6.1.0-rc4.
