### ISSUE TITLE
Changing default language not possible

### ISSUE THREAD

**Issue by dalu** [shopware/production#40]
v6.1.6
I have German and English. English is the default language.
I have no option to set the default language to German.
I can set the "channel" language to German but language settings have no field "set as default language".
I can also not delete English as a language.
Where do I even create an issue about this

**Comment by mitelg** [comment]
hey @dalu 
this is a known issue. you can find more about that in the platform repository: https://github.com/shopware/platform/issues?q=is%3Aissue+is%3Aopen+default+language
also have a look at our issue tracker https://issues.shopware.com/?search=default%20language&projects=NEXT

I will close this issue here right now. feel free to follow one of the existing tickets :blush:
