### ISSUE TITLE
Error: SQLSTATE[HY000] [2002] on "system:setup" 

### ISSUE THREAD

**Issue by Steamless** [shopware/production#59]
I get the SQLSTATE error after system:setup on "macOS Catalina v.10.15.5".

My selection:
- [0] prod & tried with [1] dev as well
- (default URL shopware.local) & tried with "http://localhost:8080"
- (default DB user app) & tried with others
- (default localhost) & tried with "127.0.0.1"
- (default port 3306)
- (default DB name shopware)

Then error appears.
` [ERROR] An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory`

If I press no on "Retry?"
I get:
`In AbstractMySQLDriver.php line 93:
  An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory`
`In PDOConnection.php line 31:
  SQLSTATE[HY000] [2002] No such file or directory`
`In PDOConnection.php line 27:
  SQLSTATE[HY000] [2002] No such file or directory`

My PHP (7.4.9) looks fine, my PHP extensions as well, just like the necessary changes on php.ini (memory_limit, etc.).
I'm currently using Docker with "shopware/platform", so I'm planning on using docker for "shopware/production" as well. Do you recommend me to use MAMP for this?
Does anyone have/had this issue? Would love to make it work ><

**Comment by Steamless** [comment]
So I realized that I was trying to start it with docker... which is not possible, since you first have to start your databank. So I started it with MAMP, since it automatically adds the databank logic... right? I'm still learning about all this things.

**Comment by bastianhilton** [comment]
I came across the same issue as above, it turns out that for some reason running the update to version 6.5.1.1 it resetted the .env file thus causing this error because it couldn't read the database. So after adding back my database url information to the .env file and running composer dump-env prod and then running the update again, it went through and I was able to restore my shopware installation.

Just in case someone comes to this in the future.
